export const CURATED_LIBRARY = [
    // Superheroes
    { name: "Batman", category: "Hero" },
    { name: "Superman", category: "Hero" },
    { name: "Spider-Man", category: "Hero" },
    { name: "Iron Man", category: "Hero" },
    { name: "Captain America", category: "Hero" },
    { name: "Thor", category: "Hero" },
    { name: "Hulk", category: "Hero" },
    { name: "Wonder Woman", category: "Hero" },
    { name: "Doctor Strange", category: "Hero" },
    { name: "Black Panther", category: "Hero" },
    { name: "Deadpool", category: "Hero" },
    { name: "Wolverine", category: "Hero" },
    { name: "Flash", category: "Hero" },
    { name: "Green Lantern", category: "Hero" },
    { name: "Aquaman", category: "Hero" },
    { name: "Scarlet Witch", category: "Hero" },
    { name: "Vision", category: "Hero" },
    { name: "Ant-Man", category: "Hero" },
    { name: "Captain Marvel", category: "Hero" },
    { name: "Daredevil", category: "Hero" },

    // Fantasy
    { name: "Gandalf", category: "Fantasy" },
    { name: "Frodo Baggins", category: "Fantasy" },
    { name: "Aragorn", category: "Fantasy" },
    { name: "Legolas", category: "Fantasy" },
    { name: "Gimli", category: "Fantasy" },
    { name: "Sauron", category: "Fantasy" },
    { name: "Galadriel", category: "Fantasy" },
    { name: "Elrond", category: "Fantasy" },
    { name: "Geralt of Rivia", category: "Fantasy" },
    { name: "Yennefer", category: "Fantasy" },
    { name: "Ciri", category: "Fantasy" },
    { name: "Dumbledore", category: "Fantasy" },
    { name: "Harry Potter", category: "Fantasy" },
    { name: "Hermione Granger", category: "Fantasy" },
    { name: "Ron Weasley", category: "Fantasy" },
    { name: "Voldemort", category: "Fantasy" },
    { name: "Hagrid", category: "Fantasy" },
    { name: "Severus Snape", category: "Fantasy" },
    { name: "Draco Malfoy", category: "Fantasy" },
    { name: "Newt Scamander", category: "Fantasy" },

    // Movie & TV
    { name: "Darth Vader", category: "Movie & TV" },
    { name: "Luke Skywalker", category: "Movie & TV" },
    { name: "Yoda", category: "Movie & TV" },
    { name: "Obi-Wan Kenobi", category: "Movie & TV" },
    { name: "Han Solo", category: "Movie & TV" },
    { name: "Princess Leia", category: "Movie & TV" },
    { name: "Kylo Ren", category: "Movie & TV" },
    { name: "Thanos", category: "Movie & TV" },
    { name: "Loki", category: "Movie & TV" },
    { name: "John Wick", category: "Movie & TV" },
    { name: "Indiana Jones", category: "Movie & TV" },
    { name: "Jack Sparrow", category: "Movie & TV" },
    { name: "Terminator", category: "Movie & TV" },
    { name: "Neo", category: "Movie & TV" },
    { name: "Morpheus", category: "Movie & TV" },
    { name: "Agent Smith", category: "Movie & TV" },
    { name: "Rocky Balboa", category: "Movie & TV" },
    { name: "Rambo", category: "Movie & TV" },
    { name: "Sherlock Holmes", category: "Movie & TV" },
    { name: "Dr. Watson", category: "Movie & TV" },

    // Anime
    { name: "Naruto Uzumaki", category: "Anime" },
    { name: "Sasuke Uchiha", category: "Anime" },
    { name: "Sakura Haruno", category: "Anime" },
    { name: "Kakashi Hatake", category: "Anime" },
    { name: "Itachi Uchiha", category: "Anime" },
    { name: "Monkey D. Luffy", category: "Anime" },
    { name: "Roronoa Zoro", category: "Anime" },
    { name: "Sanji", category: "Anime" },
    { name: "Nami", category: "Anime" },
    { name: "Trafalgar Law", category: "Anime" },
    { name: "Goku", category: "Anime" },
    { name: "Vegeta", category: "Anime" },
    { name: "Gohan", category: "Anime" },
    { name: "Piccolo", category: "Anime" },
    { name: "Frieza", category: "Anime" },
    { name: "Saitama", category: "Anime" },
    { name: "Genos", category: "Anime" },
    { name: "Light Yagami", category: "Anime" },
    { name: "L (Death Note)", category: "Anime" },
    { name: "Levi Ackerman", category: "Anime" },

    // Games
    { name: "Mario", category: "Games" },
    { name: "Luigi", category: "Games" },
    { name: "Princess Peach", category: "Games" },
    { name: "Bowser", category: "Games" },
    { name: "Link", category: "Games" },
    { name: "Zelda", category: "Games" },
    { name: "Ganondorf", category: "Games" },
    { name: "Kratos", category: "Games" },
    { name: "Atreus", category: "Games" },
    { name: "Master Chief", category: "Games" },
    { name: "Cortana", category: "Games" },
    { name: "Lara Croft", category: "Games" },
    { name: "Nathan Drake", category: "Games" },
    { name: "Solid Snake", category: "Games" },
    { name: "Raiden", category: "Games" },
    { name: "Sonic", category: "Games" },
    { name: "Tails", category: "Games" },
    { name: "Shadow", category: "Games" },
    { name: "Pikachu", category: "Games" },
    { name: "Ash Ketchum", category: "Games" },

    // Historical
    { name: "Julius Caesar", category: "Historical" },
    { name: "Alexander the Great", category: "Historical" },
    { name: "Cleopatra", category: "Historical" },
    { name: "Napoleon Bonaparte", category: "Historical" },
    { name: "Abraham Lincoln", category: "Historical" },
    { name: "George Washington", category: "Historical" },
    { name: "Winston Churchill", category: "Historical" },
    { name: "Nelson Mandela", category: "Historical" },
    { name: "Mahatma Gandhi", category: "Historical" },
    { name: "Martin Luther King Jr", category: "Historical" },
    { name: "Malcolm X", category: "Historical" },
    { name: "Queen Elizabeth I", category: "Historical" },
    { name: "Genghis Khan", category: "Historical" },
    { name: "Leonardo da Vinci", category: "Historical" },
    { name: "Joan of Arc", category: "Historical" },
    { name: "Thomas Edison", category: "Historical" },
    { name: "Nikola Tesla", category: "Historical" },
    { name: "Marie Curie", category: "Historical" },
    { name: "Albert Einstein", category: "Historical" },
    { name: "Isaac Newton", category: "Historical" },

    // Philosophers
    { name: "Socrates", category: "Philosophy" },
    { name: "Plato", category: "Philosophy" },
    { name: "Aristotle", category: "Philosophy" },
    { name: "Confucius", category: "Philosophy" },
    { name: "Lao Tzu", category: "Philosophy" },
    { name: "Sun Tzu", category: "Philosophy" },
    { name: "Friedrich Nietzsche", category: "Philosophy" },
    { name: "Karl Marx", category: "Philosophy" },
    { name: "John Locke", category: "Philosophy" },
    { name: "Immanuel Kant", category: "Philosophy" },
    { name: "René Descartes", category: "Philosophy" },
    { name: "David Hume", category: "Philosophy" },
    { name: "Thomas Hobbes", category: "Philosophy" },
    { name: "Jean-Jacques Rousseau", category: "Philosophy" },
    { name: "Voltaire", category: "Philosophy" },

    // Scientists
    { name: "Stephen Hawking", category: "Science" },
    { name: "Carl Sagan", category: "Science" },
    { name: "Richard Feynman", category: "Science" },
    { name: "Alan Turing", category: "Science" },
    { name: "Ada Lovelace", category: "Science" },
    { name: "Tim Berners-Lee", category: "Science" },
    { name: "Steve Jobs", category: "Business" },
    { name: "Bill Gates", category: "Business" },
    { name: "Elon Musk", category: "Business" },
    { name: "Mark Zuckerberg", category: "Business" },

    // Mythology
    { name: "Zeus", category: "Mythology" },
    { name: "Hera", category: "Mythology" },
    { name: "Poseidon", category: "Mythology" },
    { name: "Hades", category: "Mythology" },
    { name: "Athena", category: "Mythology" },
    { name: "Ares", category: "Mythology" },
    { name: "Apollo", category: "Mythology" },
    { name: "Artemis", category: "Mythology" },
    { name: "Odin", category: "Mythology" },
    { name: "Thor (Norse)", category: "Mythology" },
    { name: "Loki (Norse)", category: "Mythology" },
    { name: "Freya", category: "Mythology" },
    { name: "Anubis", category: "Mythology" },
    { name: "Ra", category: "Mythology" },
    { name: "Osiris", category: "Mythology" },

    // Literary
    { name: "Dracula", category: "Literary" },
    { name: "Frankenstein", category: "Literary" },
    { name: "Dorian Gray", category: "Literary" },
    { name: "Captain Ahab", category: "Literary" },
    { name: "Huckleberry Finn", category: "Literary" },
    { name: "Tom Sawyer", category: "Literary" },
    { name: "Ebenezer Scrooge", category: "Literary" },
    { name: "Jay Gatsby", category: "Literary" },
    { name: "Atticus Finch", category: "Literary" },
    { name: "Holden Caulfield", category: "Literary" },

    // AI / Sci-Fi
    { name: "HAL 9000", category: "Sci-Fi" },
    { name: "Data (Star Trek)", category: "Sci-Fi" },
    { name: "Spock", category: "Sci-Fi" },
    { name: "Captain Kirk", category: "Sci-Fi" },
    { name: "Jean-Luc Picard", category: "Sci-Fi" },
    { name: "The Doctor (Doctor Who)", category: "Sci-Fi" },
    { name: "Rick Sanchez", category: "Sci-Fi" },
    { name: "Morty Smith", category: "Sci-Fi" },
    { name: "Bender", category: "Sci-Fi" },
    { name: "Optimus Prime", category: "Sci-Fi" },

    // Leaders
    { name: "Barack Obama", category: "Leadership" },
    { name: "Donald Trump", category: "Leadership" },
    { name: "Vladimir Putin", category: "Leadership" },
    { name: "Xi Jinping", category: "Leadership" },
    { name: "Julius Nyerere", category: "Leadership" },
    { name: "Kwame Nkrumah", category: "Leadership" },
    { name: "Haile Selassie", category: "Leadership" },
    { name: "Margaret Thatcher", category: "Leadership" },
    { name: "Angela Merkel", category: "Leadership" },
    { name: "Lee Kuan Yew", category: "Leadership" },

    // Pop Culture
    { name: "Mr. Bean", category: "Pop Culture" },
    { name: "Charlie Chaplin", category: "Pop Culture" },
    { name: "Bruce Lee", category: "Pop Culture" },
    { name: "Jackie Chan", category: "Pop Culture" },
    { name: "Michael Jackson", category: "Pop Culture" },
    { name: "Cristiano Ronaldo", category: "Pop Culture" },
    { name: "Lionel Messi", category: "Pop Culture" },
    { name: "Kobe Bryant", category: "Pop Culture" },
    { name: "Serena Williams", category: "Pop Culture" },
    { name: "Muhammad Ali", category: "Pop Culture" }
];
